### ISSUE TITLE
iptv on Kodi 18.7 

### ISSUE THREAD

**Issue by greg2002mi** [Forst/iptv#8]
first of all thank you for the great job and a chance for us to enjoy russian television. Right now I live in South Korea. I installed kodi 18.7 on Raspbian (Raspberry Pi 4 4GB) in a hope to watch some russian TV. the program shows properly, and the list of channels as well. but there is no picture there. at first I suspected the issue with router settings (IGMP Snooping), but without results. then tried via hotspot from my phone, thinking of some limitations provider could make. but no success either. 
Could you please suggest any solution to my problem? Maybe pinging IPs? or changing settings?

Thank you in advance

**Comment by Mifar** [comment]
Greetings. There are almost no working iptv addresses in the public domain, you need to look for them on closed forums or in social networks. For your experiments use https://edemtv.me/, there are 100% working streams.7:51, 10 ноября 2020 г., greg2002mi <notifications@github.com>:
first of all thank you for the great job and a chance for us to enjoy russian television. Right now I live in South Korea. I installed kodi 18.7 on Raspbian (Raspberry Pi 4 4GB) in a hope to watch some russian TV. the program shows properly, and the list of channels as well. but there is no picture there. at first I suspected the issue with router settings (IGMP Snooping), but without results. then tried via hotspot from my phone, thinking of some limitations provider could make. but no success either.
Could you please suggest any solution to my problem? Maybe pinging IPs? or changing settings?
Thank you in advance

**Comment by Forst** [comment]
The playlist provided in this repository is for channels that are broadcasted officially by the specific ISP called WiFire (ex. Netbynet) in Moscow and surrounding cities only inside their network. It will not work in other providers' networks.

@Mifar's suggestion doesn't seem to be legal, therefore their comment was deleted. I do not condone copyright infringement or otherwise breaking the law.

Most TV channels only have rights to be broadcasted in Russia, therefore they aren't available abroad. Your best bet is checking the official website of the channels, for example [Channel One](https://www.1tv.ru) and [Russia-1](https://russia.tv) allow some programmes to be watched abroad.
